# Tic_Tac_Toe


In [5]:
import numpy as np 
import random 
from time import sleep 
  
# Creates an empty board 
def create_board(): 
    return(np.array([[0, 0, 0], 
                     [0, 0, 0], 
                     [0, 0, 0]])) 
  
# Check for empty places on board 

def possibilities(board): 
    l = [] 
    for i in range(len(board)): 
        for j in range(len(board)): 
              
            if board[i][j] == 0: 
                l.append((i, j)) 
    return(l) 
  
# Select a random place for the player 
def random_place(board, player): 
    selection = possibilities(board) 
    current_loc = random.choice(selection) 
    board[current_loc] = player 
    return(board) 
  
# Checks whether the player has three  
# of their marks in a horizontal row 
def row_win(board, player): 
    for x in range(len(board)): 
        win = True
          
        for y in range(len(board)): 
            if board[x, y] != player: 
                win = False
                continue
                  
        if win == True: 
            return(win) 
    return(win) 
  
# Checks whether the player has three 
# of their marks in a vertical row 
def col_win(board, player): 
    for x in range(len(board)): 
        win = True
          
        for y in range(len(board)): 
            if board[y][x] != player: 
                win = False
                continue
                  
        if win == True: 
            return(win) 
    return(win) 
  
# Checks whether the player has three 
# of their marks in a diagonal row 
def diag_win(board, player): 
    win = True
      
    for x in range(len(board)): 
        if board[x, x] != player: 
            win = False
    return(win) 
  
# Evaluates whether there is 
# a winner or a tie  
def evaluate(board): 
    winner = 0
      
    for player in [1, 2]: 
        if (row_win(board, player) or
            col_win(board,player) or 
            diag_win(board,player)): 
                 
            winner = player 
              
    if np.all(board != 0) and winner == 0: 
        winner = -1
    return winner 
  
# Main function to start the game 
def play_game(): 
    board, winner, counter = create_board(), 0, 1
    print(board) 
    sleep(2) 
      
    while winner == 0: 
        for player in [1, 2]: 
            board = random_place(board, player) 
            print("Board after " + str(counter) + " move") 
            print(board) 
            sleep(2) 
            counter += 1
            winner = evaluate(board) 
            if winner != 0: 
                break
    return(winner) 
  
# Driver Code 
print("Winner is: " + str(play_game())) 

[[0 0 0]
 [0 0 0]
 [0 0 0]]
Board after 1 move
[[0 0 0]
 [0 0 0]
 [0 0 1]]
Board after 2 move
[[0 0 0]
 [0 0 0]
 [2 0 1]]
Board after 3 move
[[1 0 0]
 [0 0 0]
 [2 0 1]]
Board after 4 move
[[1 2 0]
 [0 0 0]
 [2 0 1]]
Board after 5 move
[[1 2 0]
 [0 0 1]
 [2 0 1]]
Board after 6 move
[[1 2 0]
 [0 2 1]
 [2 0 1]]
Board after 7 move
[[1 2 1]
 [0 2 1]
 [2 0 1]]
Winner is: 1


In [6]:
from tkinter import *
import tkinter.messagebox
tk=Tk()
tk.title("-----TiC tAc ToE--------")
click=True
def checker(buttons):
    global click
    if buttons["text"] == " " and click == True:
        buttons["text"]="X"
        click= False
    elif buttons["text"]==" " and click == False:
        buttons["text"]="O"
        click=True
    elif(button1["text"]=="X" and button2["text"]=="X" and button3["text"]=="X"or
         button1["text"]=="X" and button5["text"]=="X" and button9["text"]=="X"or
         button1["text"]=="X" and button4["text"]=="X" and button7["text"]=="X"or   
         button2["text"]=="X" and button5["text"]=="X" and button8["text"]=="X"or 
         button3["text"]=="X" and button6["text"]=="X" and button9["text"]=="X"or
         button3["text"]=="X" and button5["text"]=="X" and button7["text"]=="X"or
         button4["text"]=="X" and button5["text"]=="X" and button6["text"]=="X"or
         button7["text"]=="X" and button8["text"]=="X" and button9["text"]=="X"):
        tkinter.messagebox.showinfo("Winner X", "You have just Won Game")
    elif(button1["text"]=="O" and button2["text"]=="O" and button3["text"]=="O"or
         button1["text"]=="O" and button5["text"]=="O" and button9["text"]=="O"or
         button1["text"]=="O" and button4["text"]=="O" and button7["text"]=="O"or   
         button2["text"]=="O" and button5["text"]=="O" and button8["text"]=="O"or 
         button3["text"]=="O" and button6["text"]=="O" and button9["text"]=="O"or
         button3["text"]=="O" and button5["text"]=="O" and button7["text"]=="O"or
         button4["text"]=="O" and button5["text"]=="O" and button6["text"]=="O"or
         button7["text"]=="O" and button8["text"]=="O" and button9["text"]=="O"):
        tkinter.messagebox.showinfo("Winner O", "You have just Won Game")
    else:
        tkinter.messagebox.showinfo("Draw between","X and O match")
buttons=StringVar()
button1 =Button(tk, text=" ",font=('Time 26 bold'), height=4, width=8, command= lambda:checker(button1))
button1.grid(row=1, column=0, sticky = S+N+E+W)
button2 =Button(tk, text=" ",font=('Time 26 bold'), height=4, width=8, command= lambda:checker(button2))
button2.grid(row=1, column=1, sticky = S+N+E+W)
button3 =Button(tk, text=" ",font=('Time 26 bold'), height=4, width=8, command= lambda:checker(button3))
button3.grid(row=1, column=2, sticky = S+N+E+W)
button4 =Button(tk, text=" ",font=('Time 26 bold'), height=4, width=8, command= lambda:checker(button4))
button4.grid(row=2, column=0, sticky = S+N+E+W)
button5 =Button(tk, text=" ",font=('Time 26 bold'), height=4, width=8, command= lambda:checker(button5))
button5.grid(row=2, column=1, sticky = S+N+E+W)
button6 =Button(tk, text=" ",font=('Time 26 bold'), height=4, width=8, command= lambda:checker(button6))
button6.grid(row=2, column=2, sticky = S+N+E+W)
button7 =Button(tk, text=" ",font=('Time 26 bold'), height=4, width=8, command= lambda:checker(button7))
button7.grid(row=3, column=0, sticky = S+N+E+W)
button8 =Button(tk, text=" ",font=('Time 26 bold'), height=4, width=8, command= lambda:checker(button8))
button8.grid(row=3, column=1, sticky = S+N+E+W)
button9 =Button(tk, text=" ",font=('Time 26 bold'), height=4, width=8, command= lambda:checker(button9))
button9.grid(row=3, column=2, sticky = S+N+E+W)
tk.mainloop()

In [4]:
import os
import time
import random
board=[""," "," "," "," "," "," "," "," "," "]
def print_header():
    print("""-------------- Tic Tac Toe --------------------""")
def print_board():
    print("__________")
    print("|"+board[1]+" |"+board[2]+" |"+board[3]+" |")
    print("|__|__|__|")
    print("|"+board[4]+" |"+board[5]+" |"+board[6]+" |")
    print("|__|__|__|")
    print("|"+board[7]+" |"+board[8]+" |"+board[9]+" |")
    print("|__|__|__|")

    
def is_winner(board, Player):
    if((board[1]==Player and board[2]==Player and board[3]==Player)or
       (board[1]==Player and board[4]==Player and board[7]==Player)or
       (board[1]==Player and board[5]==Player and board[9]==Player)or
       (board[2]==Player and board[5]==Player and board[8]==Player)or
       (board[3]==Player and board[6]==Player and board[9]==Player)or
       (board[3]==Player and board[5]==Player and board[7]==Player)or
       (board[4]==Player and board[5]==Player and board[6]==Player)or
       (board[7]==Player and board[8]==Player and board[9]==Player)):
        return True
    else:
        return False
def get_computer_move(board, player):
    for i in range(1,10):
        if(board[i]==" "):
            board[i]=player
            if(is_winner(board, player)):
                return i
            else:
                board[i]=" "
        
    if(board[5]==" "):
        return 5
    
    while True:
        move= random.randint(1,9)
        if(board[move]==" "):
            return move
            break
    
def is_board_full(board):
    if " " in board:
        return False
    else:
        return True
while True:
    os.system("clear")
    print_header()
    print_board()
    # User as X Player 
    choice =input("Please choose as empty space for X.")
    choice=int(choice)
    if(board[choice]==" "):
        board[choice]="X"
    else:
        print("""..............................
                                                Already Printed No Empty Space avaliable chosse another value
                                                                                                                ..........................""")
        time.sleep(2)
        
    if(is_winner(board,"X")):
        os.system("clear")
        print_header()
        print_board()
        print("X Win Congratulations: ")
        break
    
    if(is_board_full(board)):
        print("Tie Match Between X & O")
        break
    
    # Computer as a O Player
    os.system("clear")
    print_header()
    print_board()
    choice=get_computer_move(board,"O")
    if(board[choice]==" "):
        board[choice]="O"
    else:
        print("""..............................
                                                Already Printed No Empty Space avaliable chosse another value
                                                                                                                ..........................""")
        time.sleep(2)
        
    if(is_winner(board,"O")):
        os.system("clear")
        print_header()
        print_board()
        print("O Win Congratulations: ")
        break
        
        if(is_board_full(board)):
            print("Tie Match Between X & O")
            break

-------------- Tic Tac Toe --------------------
__________
|  |  |  |
|__|__|__|
|  |  |  |
|__|__|__|
|  |  |  |
|__|__|__|
Please choose as empty space for X.5
-------------- Tic Tac Toe --------------------
__________
|  |  |  |
|__|__|__|
|  |X |  |
|__|__|__|
|  |  |  |
|__|__|__|
-------------- Tic Tac Toe --------------------
__________
|O |  |  |
|__|__|__|
|  |X |  |
|__|__|__|
|  |  |  |
|__|__|__|
Please choose as empty space for X.4
-------------- Tic Tac Toe --------------------
__________
|O |  |  |
|__|__|__|
|X |X |  |
|__|__|__|
|  |  |  |
|__|__|__|
-------------- Tic Tac Toe --------------------
__________
|O |O |  |
|__|__|__|
|X |X |  |
|__|__|__|
|  |  |  |
|__|__|__|
Please choose as empty space for X.8
-------------- Tic Tac Toe --------------------
__________
|O |O |  |
|__|__|__|
|X |X |  |
|__|__|__|
|  |X |  |
|__|__|__|
..............................
                                                Already Printed No Empty Space avaliable chosse another valu

# stop watch

In [13]:
import time
def time_convert(sec):
    mins =sec//60
    sec=sec%60
    hours=mins//60
    mins=mins%60
    print("Time Lapsed = {0}:{1}:{2}".format(int(hours),int(mins),sec))
input("Press Enter a Start Time")
start_time=time.time()
input("Press Enter to End Time")
end_time=time.time()
elapsed=end_time-start_time
time_convert(elapsed)

Press Enter a Start Time
Press Enter to End Time
Time Lapsed = 0:5:30.420428037643433


In [18]:
import time
input("----Press Enter--- to start time ")

start_time=time.time()
input("----Press Enter--- to stop time ")
stop_time=time.time()
elapsed=stop_time-start_time
mins=elapsed//60
secs=elapsed%60
hours=mins//60
mins=mins%60
print("Time of Elapsed is {}:{}:{}".format(int(hours),int(mins),secs))

----Press Enter--- to start time 
----Press Enter--- to stop time 
Time of Elapsed is 0:0:5.079290390014648


# Coupon Numbers

In [41]:
import random
Coupon_Number=int(input("enter a Coupon Numbers"))
Coupon_Value = random.sample(range(0, Coupon_Number),Coupon_Number)
for i in (Coupon_Value):
    print(Coupon_Value[i])

enter a Coupon Numbers22
14
17
19
2
1
5
8
7
9
16
6
13
3
18
4
10
20
12
15
21
11
0


In [43]:
import random
def coupon_code(num_chars):
    code_chars = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'
    code = ' '
    for i in range(0,5):
        slice_start = random.randint(0,len(code_chars)-1)
        code +=code_chars[slice_start: slice_start+1]
    return(code)
    
num=6
for i in range(100):
    print(coupon_code(num))

 DnuTP
 OclYI
 TLIs6
 wbAFD
 SWr2w
 k2Spd
 oU1jG
 FRldp
 wb2es
 9Geb0
 3k6lA
 ew6MY
 0Z2pI
 Du0XD
 PM7Ug
 elDDo
 Yxyc1
 UToYn
 syutG
 qrM7j
 HK7eK
 Vj967
 5oAJv
 K85Ob
 XHVeM
 CTMQb
 KqLWM
 B3nMc
 tAWFU
 MHxg7
 vlzS2
 D1wnM
 aEABd
 hYv7V
 eOvBa
 AQr8u
 YRLWl
 M4yOZ
 Ynl3Y
 YskMN
 gXXf1
 oOqVx
 ysTyq
 0wMNw
 K91pj
 7xVvJ
 PV7R1
 bkp28
 ZgQz9
 BQt5E
 ZxrmV
 XMcnu
 e3K9x
 0m3HJ
 l23S3
 BQBZH
 mSxI7
 guW28
 F16SN
 d4CLC
 pXy7s
 l9qqo
 BmSXl
 I6qTS
 eCMHL
 5L0ir
 BVtdW
 XWnQi
 UaB4d
 CQ62o
 Nov1l
 lDSOu
 HtM4Z
 1bsKf
 pSwpE
 ulKGF
 FNWvo
 8cD4E
 0FLCv
 AmDTS
 80lRu
 pNSU3
 vN4Zo
 eItEi
 fYZNd
 zd9Qq
 bNtgs
 rVkr8
 A4898
 iaa1b
 yYbgQ
 LVqPs
 hyQtK
 nC36r
 2bEdd
 XyQMr
 uTmgP
 Tdqo9
 Br5Qf
 caTut


# Gambler


In [47]:
import random 
random.random()
import numpy as np
def integer_walk():
    money, count=10,0
    while money:
        toss= np.random.random()
        if toss<.50:
            money-=1
        if toss>.50:
            money+=1
        count +=1
    return count
sims = [integer_walk() for i in range(500)]
print(len(sims))
np.mean(sims)

500


246655.32

In [60]:
char="ABC"
for i in range(len(char)):
    for j in range(len(char)):
        for k in range(len(char)):
            if(char[i]!=char[j]!=char[k]):
                if(char[i]!=char[k]):
                    print(char[i]+char[j]+char[k])

ABC
ACB
BAC
BCA
CAB
CBA
